services:
  db:
    image: postgres:15-alpine
    container_name: lms-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    network_mode: "host"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: lms-app
    network_mode: "host"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/vian/.ssh/id_rsa:/app/id_rsa:ro

volumes:
  pgdata:
